---
global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
        # Yourself
        - 0.0.0.0:9090
  - job_name: canton
    static_configs:
      - targets:
        # Docker compose service
        - canton:19090
        labels:
          namespace: static_local
          pod: canton
          container: canton
  - job_name: sequencer4
    static_configs:
      - targets:
          # Docker compose service
          - sequencer4:19091
  - job_name: sequencer5
    static_configs:
      - targets:
          # Docker compose service
          - sequencer5:19092
  - job_name: grafana
    static_configs:
      - targets:
        # Docker compose service
        - grafana:3000
  - job_name: exporter
    static_configs:
      - targets:
        # Docker compose service
        - exporter:9100
  - job_name: loki
    static_configs:
      - targets:
        # Docker compose service
        - loki:5000
  - job_name: promtail
    static_configs:
      - targets:
        # Docker compose service
        - promtail:5100
  - job_name: postgres
    static_configs:
      - targets:
          # Docker compose service
          - postgres-exporter:9187
# Uncomment for the metrics coming from the integration tests
#  - job_name: integration_tests
#    static_configs:
#      - targets:
#          - host.docker.internal:9464
