# Copyright (c) 2023 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: 1

deleteDatasources:
  - name: Graphite
    orgId: 1

datasources:
- name: Graphite
  type: graphite
  access: proxy
  orgId: 1
  url: http://graphite:8080
  isDefault: true
  jsonData:
     graphiteVersion: "1.1"
     tlsAuth: false
     tlsAuthWithCACert: false
  version: 1
  editable: false
